import os
import sys
import platform

OS_NAME=platform.system()

env=DefaultEnvironment().Clone()
BIN_DIR=os.environ['BIN_DIR'];
LIB_DIR=os.environ['LIB_DIR'];

if OS_NAME == 'Darwin':
  env['LIBS'] = ['m'];
elif OS_NAME == 'Linux':
  env['LIBS'] = ['m'];
  
env['LINKFLAGS'] = env['OS_SUBSYSTEM_CONSOLE'] + env['LINKFLAGS'];

env.Program(os.path.join(BIN_DIR, 'image_resize'), ["resize.c"])
env.Program(os.path.join(BIN_DIR, 'image_info'), ["info.c"])
env.Program(os.path.join(BIN_DIR, 'image_to_rgb565'), ["to_rgb565.c"])



