import os
import sys

env=DefaultEnvironment().Clone()

env['LIBS'] = ['resource', 'fontbitmap', 'ui_loader', 'imageloaderbitmap', 'lua'] + env['LIBS']
env.Program('run_lua', ["run_lua.c", 'lftk_lua.c'])




