import os
import sys

LFTK_ROOT=os.environ['LFTK_ROOT'];
GTEST_ROOT=os.environ['GTEST_ROOT'];
BIN_DIR=os.environ['BIN_DIR'];

env=DefaultEnvironment().Clone();

INCLUDE_PATH = [LFTK_ROOT, 
  GTEST_ROOT,
  os.path.join(LFTK_ROOT, 'src'),  
  os.path.join(GTEST_ROOT, 'src'),
  os.path.join(GTEST_ROOT, 'include'),
  os.path.join(GTEST_ROOT, 'make')]

env['CPPPATH'] = INCLUDE_PATH
env['LIBS'] = ['resource', 'theme_gen', 'font_gen', 'common'] + env['LIBS']

SOURCES = [
 os.path.join(GTEST_ROOT, 'src/gtest-all.cc'),
] + Glob('*.cc') + Glob('*.c')

env.Program(os.path.join(BIN_DIR, 'runTest'), SOURCES);



