import os
import copy
import awtk_config as awtk

BIN_DIR=os.environ['BIN_DIR'];
LIB_DIR=os.environ['LIB_DIR'];

sources = ["fscript_widget.c"]
env=DefaultEnvironment().Clone()
env.Library(os.path.join(LIB_DIR, 'fscript_ext_widgets'), sources, LIBS=['extwidgets', 'widgets', 'base', 'tkc'])

