import os
import platform

env=DefaultEnvironment().Clone()

BIN_DIR=os.environ['BIN_DIR'];
LIB_DIR=os.environ['LIB_DIR'];

OS_NAME=os.environ['TARGET_OS'];

if OS_NAME != 'Windows':
    env['LIBS'] = ['readline'] + env['LIBS']
    
env.Program(os.path.join(BIN_DIR, 'network_shell'), Glob('*.c'))

