WIDGETS_FILES= $(AWTK_WIDGETS)/app_bar.c\
	$(AWTK_WIDGETS)/button.c\
	$(AWTK_WIDGETS)/button_group.c\
	$(AWTK_WIDGETS)/calibration_win.c\
	$(AWTK_WIDGETS)/check_button.c\
	$(AWTK_WIDGETS)/color_tile.c\
	$(AWTK_WIDGETS)/column.c\
	$(AWTK_WIDGETS)/combo_box.c\
	$(AWTK_WIDGETS)/combo_box_item.c\
	$(AWTK_WIDGETS)/dialog.c\
	$(AWTK_WIDGETS)/dialog_client.c\
	$(AWTK_WIDGETS)/dialog_title.c\
	$(AWTK_WIDGETS)/dragger.c\
	$(AWTK_WIDGETS)/edit.c\
	$(AWTK_WIDGETS)/grid.c\
	$(AWTK_WIDGETS)/grid_item.c\
	$(AWTK_WIDGETS)/group_box.c\
	$(AWTK_WIDGETS)/image.c\
	$(AWTK_WIDGETS)/label.c\
	$(AWTK_WIDGETS)/pages.c\
	$(AWTK_WIDGETS)/popup.c\
	$(AWTK_WIDGETS)/progress_bar.c\
	$(AWTK_WIDGETS)/row.c\
	$(AWTK_WIDGETS)/slider.c\
	$(AWTK_WIDGETS)/spin_box.c\
	$(AWTK_WIDGETS)/system_bar.c\
	$(AWTK_WIDGETS)/tab_button.c\
	$(AWTK_WIDGETS)/tab_button_group.c\
	$(AWTK_WIDGETS)/tab_control.c\
	$(AWTK_WIDGETS)/view.c\
	$(AWTK_WIDGETS)/window.c

