import os
import platform

OS_NAME=platform.system()
SOURCES=Glob('harfbuzz.cc')
LIB_DIR=os.environ['LIB_DIR']
TOOLS_NAME = os.environ['TOOLS_NAME']

env=DefaultEnvironment().Clone()

if (TOOLS_NAME == 'mingw' or OS_NAME == 'Darwin' or OS_NAME == 'Linux'):
  env['CCFLAGS'] = env['CCFLAGS'] + ' -O3 -DHAVE_CONFIG_H -std=gnu++11'
else:
  opt_flag = '/O2 /Ob2'
  if '/Od' in env['CCFLAGS']:
    opt_flag = '/Od'
  env['CCFLAGS'] = env['CCFLAGS'] + ' /DHAVE_CONFIG_H ' + opt_flag + ' /W1 /GR /Gd /nologo /Gm- /GS /Zc:wchar_t /Zc:inline '

env.Library(os.path.join(LIB_DIR, 'harfbuzz'), SOURCES)

