    <view name="view" x="0" y="0" w="100%" h="100%" style:normal:bg_color="#A8D08D">
      <image name="image" x="20%" y="30%" w="15%" h="15%" draw_type="icon" image="message" animation="rotation(duration=1000,repeat_times=0,easing=linear,from=0,to=3.14)"/>
      <image name="image1" x="80%" y="30%" w="15%" h="15%" draw_type="icon" image="message" animation="rotation(duration=1000,repeat_times=0,easing=linear,from=0,to=3.14)"/>
      <hscroll_label name="hscroll_label" x="10%" y="60%" w="50%" h="10%" loop="true" text="test test test test test test test test test test test test"/>
    </view>
    <view name="view1" x="0" y="0" w="100%" h="100%" style:normal:bg_color="#FFD964">
      <image name="image4" x="30%" y="30%" w="15%" h="15%" draw_type="icon" image="message" animation="rotation(duration=1000,repeat_times=0,easing=linear,from=0,to=3.14)"/>
    </view>
    <view name="view2" x="0" y="0" w="100%" h="100%" style:normal:bg_color="#F4B284">
      <image name="image3" x="30%" y="30%" w="15%" h="15%" draw_type="icon" image="message" animation="rotation(duration=1000,repeat_times=0,easing=linear,from=0,to=3.14)"/>
      <hscroll_label name="hscroll_label1"x="10%" y="60%" w="50%" h="10%" text="test test test test test test test test test test test test test test test "/>
    </view>