import os
import sys

env=DefaultEnvironment().Clone()
BIN_DIR=os.environ['BIN_DIR'];
LIB_DIR=os.environ['LIB_DIR'];

env.Library(os.path.join(LIB_DIR, 'theme_gen'), ['theme_gen.cc', 'xml_theme_gen.cc'])
env['LIBS'] = ['theme_gen', 'common'] + env['LIBS'];
env['LINKFLAGS'] = env['OS_SUBSYSTEM_CONSOLE'] + env['LINKFLAGS'];

env.Program(os.path.join(BIN_DIR, 'themegen'), ['main.cc'])



