import os
import sys

env=DefaultEnvironment().Clone()
BIN_DIR=os.environ['BIN_DIR'];
LIB_DIR=os.environ['LIB_DIR'];

env.Library(os.path.join(LIB_DIR, 'image_gen'), ['image_gen.c']);
env['LIBS'] = ['image_gen', 'common'] + env['LIBS']
env['LINKFLAGS'] = env['OS_SUBSYSTEM_CONSOLE'] + env['LINKFLAGS'];
env.Program(os.path.join(BIN_DIR, 'imagegen'), ["main.c"])



