import os
import sys

env=DefaultEnvironment().Clone()
BIN_DIR=os.environ['BIN_DIR'];
LIB_DIR=os.environ['LIB_DIR'];

env.Library(os.path.join(LIB_DIR, 'font_gen'), ["font_gen.c"])
env['LIBS'] = ['font_gen', 'common'] + env['LIBS']
env['LINKFLAGS'] = env['OS_SUBSYSTEM_CONSOLE'] + env['LINKFLAGS'];

env.Program(os.path.join(BIN_DIR, 'fontgen'), ["main.c"])
env.Program(os.path.join(BIN_DIR, 'genascii'), ["gen_ascii.c"])



