BASE_FILES=$(AWTK_BASE)/assets_manager.c\
	$(AWTK_BASE)/bitmap.c\
	$(AWTK_BASE)/canvas.c\
	$(AWTK_BASE)/children_layouter.c\
	$(AWTK_BASE)/clip_board.c\
	$(AWTK_BASE)/enums.c\
	$(AWTK_BASE)/event_queue.c\
	$(AWTK_BASE)/events.c\
	$(AWTK_BASE)/font.c\
	$(AWTK_BASE)/font_loader.c\
	$(AWTK_BASE)/font_manager.c\
	$(AWTK_BASE)/glyph_cache.c\
	$(AWTK_BASE)/idle.c\
	$(AWTK_BASE)/idle_info.c\
	$(AWTK_BASE)/idle_manager.c\
	$(AWTK_BASE)/image_base.c\
	$(AWTK_BASE)/image_loader.c\
	$(AWTK_BASE)/image_manager.c\
	$(AWTK_BASE)/input_device_status.c\
	$(AWTK_BASE)/input_engine.c\
	$(AWTK_BASE)/input_method.c\
	$(AWTK_BASE)/layout.c\
	$(AWTK_BASE)/lcd.c\
	$(AWTK_BASE)/lcd_profile.c\
	$(AWTK_BASE)/line_break.c\
	$(AWTK_BASE)/locale_info.c\
	$(AWTK_BASE)/main_loop.c\
	$(AWTK_BASE)/rom_fs.c\
	$(AWTK_BASE)/self_layouter.c\
	$(AWTK_BASE)/style.c\
	$(AWTK_BASE)/style_const.c\
	$(AWTK_BASE)/style_factory.c\
	$(AWTK_BASE)/suggest_words.c\
	$(AWTK_BASE)/system_info.c\
	$(AWTK_BASE)/theme.c\
	$(AWTK_BASE)/timer.c\
	$(AWTK_BASE)/timer_info.c\
	$(AWTK_BASE)/timer_manager.c\
	$(AWTK_BASE)/ui_builder.c\
	$(AWTK_BASE)/ui_loader.c\
	$(AWTK_BASE)/velocity.c\
	$(AWTK_BASE)/vgcanvas.c\
	$(AWTK_BASE)/widget.c\
	$(AWTK_BASE)/widget_animator.c\
	$(AWTK_BASE)/widget_animator_factory_null.c\
	$(AWTK_BASE)/widget_animator_manager.c\
	$(AWTK_BASE)/widget_factory.c\
	$(AWTK_BASE)/widget_pool.c\
	$(AWTK_BASE)/widget_vtable.c\
	$(AWTK_BASE)/window_animator.c\
	$(AWTK_BASE)/window_animator_factory.c\
	$(AWTK_BASE)/window_base.c\
	$(AWTK_BASE)/dialog_highlighter.c\
	$(AWTK_BASE)/dialog_highlighter_factory.c\
	$(AWTK_BASE)/window_manager.c

