#
# This makefile can be used to build Win32 application under Cygwin
#

all:
	cd aa_demo; make
	cd aa_test; make
	cd agg2d_demo; make
	cd alpha_gradient; make
	cd alpha_mask; make
	cd alpha_mask2; make
	cd alpha_mask3; make
	cd bezier_div; make
	cd bspline; make
	cd circles; make
	cd compositing; make
	cd component_rendering; make
	cd conv_contour; make
	cd conv_dash_marker; make
	cd conv_stroke; make
	cd distortions; make
	cd gamma_correction; make
	cd gamma_ctrl; make
	cd gouraud; make
	cd gpc_test; make
	cd gradients; make
	cd graph_test; make
	cd idea; make
	cd image_alpha; make
	cd image_filters; make
	cd image_filters2; make
	cd image_fltr_graph; make
	cd image_transforms; make
	cd image_perspective; make
	cd image_resample; make
	cd image1; make
	cd line_patterns; make
	cd lion; make
	cd lion_lens; make
	cd lion_outline; make
	cd mol_view; make
	cd multi_clip; make
	cd pattern_fill; make
	cd perspective; make
	cd polymorphic_renderer; make
	cd raster_text; make
	cd rasterizers; make
	cd rasterizers2; make
	cd rounded_rect; make
	cd scanline_boolean; make
	cd scanline_boolean2; make
	cd simple_blur; make
	cd trans_polar; make
	cd trans_curve1; make
	cd trans_curve2; make
	cd truetype_test; make
clean:
	cd aa_demo; make clean
	cd aa_test; make clean
	cd alpha_gradient; make clean
	cd alpha_mask; make clean
	cd alpha_mask2; make clean
	cd alpha_mask3; make clean
	cd bezier_div; make clean
	cd bspline; make clean
	cd circles; make clean
	cd compositing; make clean
	cd component_rendering; make clean
	cd conv_contour; make clean
	cd conv_dash_marker; make clean
	cd conv_stroke; make clean
	cd distortions; make clean
	cd gamma_correction; make clean
	cd gamma_ctrl; make clean
	cd gouraud; make clean
	cd gpc_test; make clean
	cd gradients; make clean
	cd graph_test; make clean
	cd idea; make clean
	cd image_alpha; make clean
	cd image_filters; make clean
	cd image_filters2; make clean
	cd image_fltr_graph; make clean
	cd image_perspective; make clean
	cd image_resample; make clean
	cd image_transforms; make clean
	cd images1; make clean
	cd line_patterns; make clean
	cd lion; make clean
	cd lion_lens; make clean
	cd lion_outline; make clean
	cd mol_view; make clean
	cd multi_clip; make clean
	cd pattern_fill; make clean
	cd perspective; make clean
	cd polymorphic_renderer; make clean
	cd raster_text; make clean
	cd rasterizers; make clean
	cd rasterizers2; make clean
	cd rounded_rect; make clean
	cd scanline_boolean; make clean
	cd scanline_boolean2; make clean
	cd simple_blur; make clean
	cd trans_polar; make clean
	cd trans_curve1; make clean
	cd trans_curve2; make clean
	cd truetype_test; make clean
