import os
import copy
import platform

OS_NAME=os.environ['TARGET_OS'];
BIN_DIR=os.environ['BIN_DIR'];
LIB_DIR=os.environ['LIB_DIR'];

sources = Glob('*.c') 
if OS_NAME == 'Windows':
  sources += Glob('windows/*.c') + Glob('windows/*.cpp')
elif OS_NAME == 'Darwin':
  sources += Glob('macos/*.c') + Glob('macos/*.cpp')
elif OS_NAME == 'Linux':
  sources += Glob('linux/*.c') + Glob('linux/*.cpp')

env=DefaultEnvironment().Clone()
env.Library(os.path.join(LIB_DIR, 'hal'), sources, LIBS=['tkc'])

