import os
import copy

BIN_DIR=os.environ['BIN_DIR'];
LIB_DIR=os.environ['LIB_DIR'];

sources = Glob('*.c');

env=DefaultEnvironment().Clone()

env.Library(os.path.join(LIB_DIR, 'compressors'), sources, LIBS=[])

