import os

env = DefaultEnvironment().Clone()
LIB_DIR = os.environ['LIB_DIR'];
BIN_DIR = os.environ['BIN_DIR'];

CPPPATH = ['include'] + env['CPPPATH']

SOURCES = Glob('src/*.c')
env.Library(os.path.join(LIB_DIR, 'svgtiny'), SOURCES, CPPPATH = CPPPATH);

