import os
import sys

env=DefaultEnvironment().Clone()
BIN_DIR=os.environ['BIN_DIR'];

env['LIBS'] = ['common'] + env['LIBS']
env['LINKFLAGS'] = env['OS_SUBSYSTEM_CONSOLE'] + env['LINKFLAGS'];
env.Program(os.path.join(BIN_DIR, 'xml_to_ui'), ["xml_to_ui.c"])



