import os
import sys

env=DefaultEnvironment().Clone()
BIN_DIR=os.environ['BIN_DIR'];
LIB_DIR=os.environ['LIB_DIR'];

env['LIBS'] = ['common'] + env['LIBS']

env.Program(os.path.join(BIN_DIR, 'resgen'), ["main.c"])



