    <view x="0" y="0" w="100%" h="100%" children_layout="default(w=60,h=60,m=5,s=10)">
      <button name="close" style="grid_item"> 
        <image draw_type="icon" x="center" y="top" w="100%" h="80%" image="message" />
        <label x="center" y="bottom" w="100%" h="30%" text="Close" />
      </button>
      <button name="open:back_to_home" style="grid_item"> 
        <image draw_type="icon" x="center" y="top" w="100%" h="80%" image="message" />
        <label x="center" y="bottom" w="100%" h="30%" text="Home" />
      </button>
      <button name="btn03" style="grid_item"> 
        <image draw_type="icon" x="center" y="top" w="100%" h="80%" image="message" />
        <label x="center" y="bottom" w="100%" h="30%" text="0.3" />
      </button>
      <button name="btn04" style="grid_item"> 
        <image draw_type="icon" x="center" y="top" w="100%" h="80%" image="message" />
        <label x="center" y="bottom" w="100%" h="30%" text="0.4" />
      </button>
      <button name="btn05" style="grid_item"> 
        <image draw_type="icon" x="center" y="top" w="100%" h="80%" image="message" />
        <label x="center" y="bottom" w="100%" h="30%" text="0.5" />
      </button>
      <button name="btn06" style="grid_item"> 
        <image draw_type="icon" x="center" y="top" w="100%" h="80%" image="message" />
        <label x="center" y="bottom" w="100%" h="30%" text="0.6" />
      </button>
      <button name="btn07" style="grid_item"> 
        <image draw_type="icon" x="center" y="top" w="100%" h="80%" image="message" />
        <label x="center" y="bottom" w="100%" h="30%" text="0.7" />
      </button>
      <button name="btn08" style="grid_item"> 
        <image draw_type="icon" x="center" y="top" w="100%" h="80%" image="message" />
        <label x="center" y="bottom" w="100%" h="30%" text="0.8" />
      </button>
    </view>
    
    <view x="0" y="0" w="100%" h="100%" children_layout="default(w=60,h=60,m=5,s=10)">
      <button name="btn11" style="grid_item"> 
        <image draw_type="icon" x="center" y="top" w="100%" h="80%" image="message" />
        <label x="center" y="bottom" w="100%" h="30%" text="1.1" />
      </button>
      <button name="btn12" style="grid_item"> 
        <image draw_type="icon" x="center" y="top" w="100%" h="80%" image="message" />
        <label x="center" y="bottom" w="100%" h="30%" text="1.2" />
      </button>
      <button name="btn13" style="grid_item"> 
        <image draw_type="icon" x="center" y="top" w="100%" h="80%" image="message" />
        <label x="center" y="bottom" w="100%" h="30%" text="1.3" />
      </button>
      <button name="btn14" style="grid_item"> 
        <image draw_type="icon" x="center" y="top" w="100%" h="80%" image="message" />
        <label x="center" y="bottom" w="100%" h="30%" text="1.4" />
      </button>
      <button name="btn15" style="grid_item"> 
        <image draw_type="icon" x="center" y="top" w="100%" h="80%" image="message" />
        <label x="center" y="bottom" w="100%" h="30%" text="1.5" />
      </button>
      <button name="btn16" style="grid_item"> 
        <image draw_type="icon" x="center" y="top" w="100%" h="80%" image="message" />
        <label x="center" y="bottom" w="100%" h="30%" text="1.6" />
      </button>
      <button name="btn17" style="grid_item"> 
        <image draw_type="icon" x="center" y="top" w="100%" h="80%" image="message" />
        <label x="center" y="bottom" w="100%" h="30%" text="1.7" />
      </button>
      <button name="btn18" style="grid_item"> 
        <image draw_type="icon" x="center" y="top" w="100%" h="80%" image="message" />
        <label x="center" y="bottom" w="100%" h="30%" text="1.8" />
      </button>
    </view>
    
    <view x="0" y="0" w="100%" h="100%" children_layout="default(w=60,h=60,m=5,s=10)">
      <button name="btn21" style="grid_item"> 
        <image draw_type="icon" x="center" y="top" w="100%" h="80%" image="message" />
        <label x="center" y="bottom" w="100%" h="30%" text="2.1" />
      </button>
      <button name="btn22" style="grid_item"> 
        <image draw_type="icon" x="center" y="top" w="100%" h="80%" image="message" />
        <label x="center" y="bottom" w="100%" h="30%" text="2.2" />
      </button>
      <button name="btn23" style="grid_item"> 
        <image draw_type="icon" x="center" y="top" w="100%" h="80%" image="message" />
        <label x="center" y="bottom" w="100%" h="30%" text="2.3" />
      </button>
      <button name="btn24" style="grid_item"> 
        <image draw_type="icon" x="center" y="top" w="100%" h="80%" image="message" />
        <label x="center" y="bottom" w="100%" h="30%" text="2.4" />
      </button>
      <button name="btn25" style="grid_item"> 
        <image draw_type="icon" x="center" y="top" w="100%" h="80%" image="message" />
        <label x="center" y="bottom" w="100%" h="30%" text="2.5" />
      </button>
      <button name="btn26" style="grid_item"> 
        <image draw_type="icon" x="center" y="top" w="100%" h="80%" image="message" />
        <label x="center" y="bottom" w="100%" h="30%" text="2.6" />
      </button>
      <button name="btn27" style="grid_item"> 
        <image draw_type="icon" x="center" y="top" w="100%" h="80%" image="message" />
        <label x="center" y="bottom" w="100%" h="30%" text="2.7" />
      </button>
      <button name="btn28" style="grid_item"> 
        <image draw_type="icon" x="center" y="top" w="100%" h="80%" image="message" />
        <label x="center" y="bottom" w="100%" h="30%" text="2.8" />
      </button>
    </view>
