/*
 * Automatically generated by SheenBidiGenerator tool.
 * DO NOT EDIT!!
 */

#ifndef _SB_INTERNAL_BIDI_TYPE_LOOKUP_H
#define _SB_INTERNAL_BIDI_TYPE_LOOKUP_H

#include <API/SBBase.h>
#include <API/SBCodepoint.h>

SB_INTERNAL SBBidiType LookupBidiType(SBCodepoint codepoint);

#endif
