import os
import platform

def joinPath(root, subdir):
  return os.path.normpath(os.path.join(root, subdir))
env=DefaultEnvironment().Clone()
LIB_DIR=os.environ['LIB_DIR'];
BIN_DIR=os.environ['BIN_DIR'];
CCFLAGS=os.environ['CCFLAGS'];
TK_3RD_ROOT=os.environ['TK_3RD_ROOT'];
OS_NAME=os.environ['TARGET_OS'];

env.Library(os.path.join(LIB_DIR, 'nanovg'), Glob('base/*.c'))
env['LINKFLAGS'] = env['OS_SUBSYSTEM_CONSOLE'] + env['LINKFLAGS'];

NANOVG_BACKEND=os.environ['NANOVG_BACKEND'];

if NANOVG_BACKEND == 'AGGE':
  env.Library(os.path.join(LIB_DIR, 'nanovg-agge'), Glob('agge/*.cpp'))
  
#  env['LIBS'] = ['nanovg-agge', 'agge', 'nanovg'] + env['LIBS']
#  env.Program(os.path.join(BIN_DIR, 'agge_stroke'), Glob('demos/agge_stroke.c'));
#  env.Program(os.path.join(BIN_DIR, 'agge_fill'), Glob('demos/agge_fill.c'));
#  env.Program(os.path.join(BIN_DIR, 'agge_draw_image'), Glob('demos/agge_draw_image.c'));

