#!/usr/bin/env python3
"""
Generate AWTK Arabic shaping support tables from Unicode Character Database:
  - ArabicShaping.txt -> joining type ranges (uint8 bit layout compatible with UBA shaping step)
  - UnicodeData.txt -> Bidi_Class in {BN,LRE,RLE,LRO,RLO,PDF,LRI,RLI,FSI,PDI} ranges
  - Presentation mapping from bundled FriBidi arabic-shaping.tab.i (numeric facts only)

Outputs (default paths relative to repo root):
  src/base/awtk_arabic_unicode_inc.h
"""
from __future__ import annotations

import os
import re
import sys

REPO = os.path.normpath(os.path.join(os.path.dirname(__file__), ".."))
OUT = os.path.join(REPO, "src", "base", "awtk_arabic_unicode_inc.h")
AR_SHAPING = os.path.join(REPO, "tools", "data", "ArabicShaping.txt")
FRIBIDI_AR_SHAP = os.path.join(REPO, "3rd", "fribidi", "arabic-shaping.tab.i")

# Same bit layout as Unicode / UBA shaping implementations use internally:
MASK_JOINS_RIGHT = 0x01
MASK_JOINS_LEFT = 0x02
MASK_ARAB_SHAPES = 0x04
MASK_TRANSPARENT = 0x08
MASK_IGNORED = 0x10

JOIN_MAP = {
    "U": 0,
    "R": MASK_JOINS_RIGHT | MASK_ARAB_SHAPES,
    "D": MASK_JOINS_RIGHT | MASK_JOINS_LEFT | MASK_ARAB_SHAPES,
    "L": MASK_JOINS_LEFT | MASK_ARAB_SHAPES,
    "C": MASK_JOINS_RIGHT | MASK_JOINS_LEFT,
    "T": MASK_TRANSPARENT | MASK_ARAB_SHAPES,
    "G": MASK_IGNORED,
}


def merge_ranges(items: list[tuple[int, int, int]]) -> list[tuple[int, int, int]]:
    items = sorted(items, key=lambda x: (x[0], x[2]))
    out: list[tuple[int, int, int]] = []
    for lo, hi, val in items:
        if out and out[-1][2] == val and lo == out[-1][1] + 1:
            out[-1] = (out[-1][0], hi, val)
        else:
            out.append((lo, hi, val))
    return out


def parse_arabic_shaping(path: str) -> list[tuple[int, int, int]]:
    ranges: list[tuple[int, int, int]] = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = [p.strip() for p in line.split(";")]
            if len(parts) < 3:
                continue
            try:
                cp = int(parts[0], 16)
            except ValueError:
                continue
            jt = parts[2]
            if jt not in JOIN_MAP:
                continue
            ranges.append((cp, cp, JOIN_MAP[jt]))
    return merge_ranges(ranges)


def parse_unicode_data_bidi_explicit_bn(ud_path: str) -> list[tuple[int, int]]:
    want = {"BN", "LRE", "RLE", "LRO", "RLO", "PDF", "LRI", "RLI", "FSI", "PDI"}
    ranges: list[tuple[int, int]] = []
    cur_lo = cur_hi = None
    with open(ud_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            parts = line.split(";")
            if len(parts) < 5:
                continue
            cp = int(parts[0], 16)
            bcls = parts[4]
            if bcls not in want:
                continue
            if cur_lo is None:
                cur_lo = cur_hi = cp
            elif cp == cur_hi + 1:
                cur_hi = cp
            else:
                ranges.append((cur_lo, cur_hi))
                cur_lo = cur_hi = cp
    if cur_lo is not None:
        ranges.append((cur_lo, cur_hi))
    return ranges


def parse_fribidi_ar_shap(path: str) -> list[tuple[int, int, int, int]]:
    rows: list[tuple[int, int, int, int]] = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            m = re.search(r"\{([^}]+)\}", line)
            if not m:
                continue
            inner = m.group(1)
            nums = [int(x, 16) for x in re.findall(r"0x[0-9a-fA-F]+", inner)]
            if len(nums) != 4:
                continue
            rows.append((nums[0], nums[1], nums[2], nums[3]))
    return rows


def emit(path: str, join_ranges, bn_ranges, pres_rows) -> None:
    lines = [
        "/*",
        " * Machine-generated by tools/gen_awtk_arabic_unicode_inc.py",
        " * Joining_Type: Unicode ArabicShaping.txt",
        " * explicit/BN ranges: Unicode UnicodeData.txt (Bidi_Class)",
        " * Presentation quadruples: same codepoint mapping as Unicode Arabic Presentation Forms-B",
        " *   (extracted numerically from 3rd/fribidi/arabic-shaping.tab.i for consistency).",
        " * Regenerate after Unicode upgrade: place ArabicShaping.txt under tools/data/ and pass",
        " * path to UnicodeData.txt as argv[1].",
        " */",
        "#ifndef AWTK_ARABIC_UNICODE_INC_H",
        "#define AWTK_ARABIC_UNICODE_INC_H",
        "",
        "#include \"base/types_def.h\"",
        "",
        "typedef struct _awtk_ar_join_range_t {",
        "  uint32_t lo;",
        "  uint32_t hi;",
        "  uint8_t prop;",
        "} awtk_ar_join_range_t;",
        "",
        f"#define AWTK_AR_PRES_ROW_COUNT {len(pres_rows)}u",
        "",
        "static const awtk_ar_join_range_t g_awtk_ar_join_ranges[] = {",
    ]
    for lo, hi, p in join_ranges:
        lines.append(f"  {{ {lo}u, {hi}u, {p}u }},")
    lines.append("};")
    lines.append(f"#define AWTK_AR_JOIN_RANGE_COUNT {len(join_ranges)}u")
    lines.append("")
    lines.append("typedef struct _awtk_ar_bn_range_t {")
    lines.append("  uint32_t lo;")
    lines.append("  uint32_t hi;")
    lines.append("} awtk_ar_bn_range_t;")
    lines.append("")
    lines.append("static const awtk_ar_bn_range_t g_awtk_ar_explicit_bn_ranges[] = {")
    for lo, hi in bn_ranges:
        lines.append(f"  {{ {lo}u, {hi}u }},")
    lines.append("};")
    lines.append(f"#define AWTK_AR_EXPLICIT_BN_RANGE_COUNT {len(bn_ranges)}u")
    lines.append("")
    lines.append("static const uint32_t g_awtk_ar_pres[][4] = {")
    for a, b, c, d in pres_rows:
        lines.append(f"  {{ 0x{a:04x}u, 0x{b:04x}u, 0x{c:04x}u, 0x{d:04x}u }},")
    lines.append("};")
    lines.append("")
    lines.append("#endif /* AWTK_ARABIC_UNICODE_INC_H */")
    lines.append("")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def main() -> int:
    ud = sys.argv[1] if len(sys.argv) > 1 else None
    if ud is None or not os.path.isfile(ud):
        print("Usage: gen_awtk_arabic_unicode_inc.py /path/to/UnicodeData.txt", file=sys.stderr)
        print("Download: https://www.unicode.org/Public/UNIDATA/UnicodeData.txt", file=sys.stderr)
        return 1
    if not os.path.isfile(AR_SHAPING):
        print("Missing", AR_SHAPING, file=sys.stderr)
        return 1
    if not os.path.isfile(FRIBIDI_AR_SHAP):
        print("Missing", FRIBIDI_AR_SHAP, file=sys.stderr)
        return 1
    join_ranges = parse_arabic_shaping(AR_SHAPING)
    bn_ranges = parse_unicode_data_bidi_explicit_bn(ud)
    pres_rows = parse_fribidi_ar_shap(FRIBIDI_AR_SHAP)
    emit(OUT, join_ranges, bn_ranges, pres_rows)
    print("Wrote", OUT)
    print("join ranges:", len(join_ranges), "explicit_bn:", len(bn_ranges), "pres rows:", len(pres_rows))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
