#include "awtk.h"
#include "base/assets_manager.h"
#ifndef WITH_FS_RES
#include "inc/styles/edit.data"
#include "inc/styles/keyboard.data"
#include "inc/styles/color.data"
#include "inc/styles/tab_bottom.data"
#include "inc/styles/calibration.data"
#include "inc/styles/tab_list.data"
#include "inc/styles/default.data"
#include "inc/styles/big_font.data"
#include "inc/styles/tab_top_compact.data"
#include "inc/styles/dialog.data"
#include "inc/styles/tab_top.data"
#include "inc/styles/button.data"
#include "inc/styles/tab_bottom_compact.data"
#include "inc/ui/kb_ascii.data"
#include "inc/ui/rich_text1.data"
#include "inc/ui/color_picker_simple.data"
#include "inc/ui/combo_box.data"
#include "inc/ui/kb_phone.data"
#include "inc/ui/main.data"
#include "inc/ui/scroll_bar.data"
#include "inc/ui/lua.data"
#include "inc/ui/preload.data"
#include "inc/ui/images.data"
#include "inc/ui/edit.data"
#include "inc/ui/locale.data"
#include "inc/ui/kb_int.data"
#include "inc/ui/tab_control.data"
#include "inc/ui/animation.data"
#include "inc/ui/keyboard.data"
#include "inc/ui/kb_hex.data"
#include "inc/ui/color.data"
#include "inc/ui/color_picker.data"
#include "inc/ui/switch.data"
#include "inc/ui/dragger.data"
#include "inc/ui/dialog2.data"
#include "inc/ui/color_picker_hsv.data"
#include "inc/ui/tab_bottom.data"
#include "inc/ui/list_view_m.data"
#include "inc/ui/calibration_win.data"
#include "inc/ui/memtest.data"
#include "inc/ui/kb_float.data"
#include "inc/ui/htranslate.data"
#include "inc/ui/list_view_vh.data"
#include "inc/ui/rich_text.data"
#include "inc/ui/scroll_view.data"
#include "inc/ui/tab_list.data"
#include "inc/ui/animator.data"
#include "inc/ui/scroll_view_h.data"
#include "inc/ui/scroll_bar_h.data"
#include "inc/ui/spinbox.data"
#include "inc/ui/text_selector.data"
#include "inc/ui/big_font.data"
#include "inc/ui/tab_top_compact.data"
#include "inc/ui/slide_view_h.data"
#include "inc/ui/selectm.data"
#include "inc/ui/list_view.data"
#include "inc/ui/basic.data"
#include "inc/ui/auto_play.data"
#include "inc/ui/guage.data"
#include "inc/ui/color_picker_full.data"
#include "inc/ui/dialog1.data"
#include "inc/ui/fade.data"
#include "inc/ui/image_list.data"
#include "inc/ui/select1.data"
#include "inc/ui/bottom.data"
#include "inc/ui/image_animation.data"
#include "inc/ui/slide_view.data"
#include "inc/ui/time_clock.data"
#include "inc/ui/tab_top.data"
#include "inc/ui/slide_view_v.data"
#include "inc/ui/top.data"
#include "inc/ui/button.data"
#include "inc/ui/list_view_d.data"
#include "inc/ui/vtranslate.data"
#include "inc/ui/kb_ufloat.data"
#include "inc/ui/kb_default.data"
#include "inc/ui/rich_text2.data"
#include "inc/ui/list_view_h.data"
#include "inc/ui/color_picker_rgb.data"
#include "inc/ui/tab_bottom_compact.data"
#include "inc/ui/kb_uint.data"
#include "inc/ui/scroll_view_v.data"
#ifdef WITH_STB_IMAGE
#include "inc/images/ani6.res"
#include "inc/images/checked.res"
#include "inc/images/shift.res"
#include "inc/images/ani7.res"
#include "inc/images/ania.res"
#include "inc/images/anic.res"
#include "inc/images/earth.res"
#include "inc/images/ani5.res"
#include "inc/images/contact.res"
#include "inc/images/slider_fg.res"
#include "inc/images/contact_active.res"
#include "inc/images/dialog_title.res"
#include "inc/images/ani4.res"
#include "inc/images/anib.res"
#include "inc/images/me_active.res"
#include "inc/images/arrow_up_n.res"
#include "inc/images/left_on.res"
#include "inc/images/arrow_right_p.res"
#include "inc/images/slider_v_fg.res"
#include "inc/images/empty.res"
#include "inc/images/rgba.res"
#include "inc/images/edit_clear_p.res"
#include "inc/images/arrow_up_o.res"
#include "inc/images/ani1.res"
#include "inc/images/arrow_left_o.res"
#include "inc/images/ani3.res"
#include "inc/images/clock_second.res"
#include "inc/images/slider_drag_o.res"
#include "inc/images/guage_bg.res"
#include "inc/images/ani2.res"
#include "inc/images/arrow_left_n.res"
#include "inc/images/middle_on.res"
#include "inc/images/bricks.res"
#include "inc/images/msg.res"
#include "inc/images/play_o.res"
#include "inc/images/play_n.res"
#include "inc/images/msg_active.res"
#include "inc/images/radio_checked.res"
#include "inc/images/question.res"
#include "inc/images/discovery_active.res"
#include "inc/images/shifton.res"
#include "inc/images/check.res"
#include "inc/images/cursor.res"
#include "inc/images/me.res"
#include "inc/images/info.res"
#include "inc/images/red_btn_p.res"
#include "inc/images/middle_off.res"
#include "inc/images/arrow_down_n.res"
#include "inc/images/green_btn_o.res"
#include "inc/images/green_btn_n.res"
#include "inc/images/muted.res"
#include "inc/images/arrow_down_o.res"
#include "inc/images/rgb.res"
#include "inc/images/unmuted.res"
#include "inc/images/right_off.res"
#include "inc/images/message.res"
#include "inc/images/3.res"
#include "inc/images/play_p.res"
#include "inc/images/2.res"
#include "inc/images/slider_bg.res"
#include "inc/images/right_on.res"
#include "inc/images/guage_pointer.res"
#include "inc/images/bg800x480.res"
#include "inc/images/left_off.res"
#include "inc/images/1.res"
#include "inc/images/red_btn_o.res"
#include "inc/images/slider_drag.res"
#include "inc/images/unchecked.res"
#include "inc/images/red_btn_n.res"
#include "inc/images/arrow_down_p.res"
#include "inc/images/slider_v_bg.res"
#include "inc/images/warn.res"
#include "inc/images/green_btn_p.res"
#include "inc/images/switch.res"
#include "inc/images/radio_unchecked.res"
#include "inc/images/clock_bg.res"
#include "inc/images/clock_minute.res"
#include "inc/images/cross.res"
#include "inc/images/clock.res"
#include "inc/images/find.res"
#include "inc/images/ani9.res"
#include "inc/images/arrow_up_p.res"
#include "inc/images/edit_clear_o.res"
#include "inc/images/arrow_right_n.res"
#include "inc/images/discovery.res"
#include "inc/images/arrow_right_o.res"
#include "inc/images/edit_clear_n.res"
#include "inc/images/ani8.res"
#include "inc/images/logo.res"
#include "inc/images/slider_drag_p.res"
#include "inc/images/backspace.res"
#include "inc/images/arrow_left_p.res"
#include "inc/images/clock_hour.res"
#else
#include "inc/images/arrow_right_o.data"
#include "inc/images/slider_bg.data"
#include "inc/images/ani3.data"
#include "inc/images/muted.data"
#include "inc/images/earth.data"
#include "inc/images/shift.data"
#include "inc/images/arrow_up_p.data"
#include "inc/images/bg800x480.data"
#include "inc/images/discovery_active.data"
#include "inc/images/right_on.data"
#include "inc/images/discovery.data"
#include "inc/images/rgb.data"
#include "inc/images/ani2.data"
#include "inc/images/find.data"
#include "inc/images/slider_fg.data"
#include "inc/images/left_on.data"
#include "inc/images/1.data"
#include "inc/images/question.data"
#include "inc/images/guage_bg.data"
#include "inc/images/arrow_right_n.data"
#include "inc/images/clock_bg.data"
#include "inc/images/me_active.data"
#include "inc/images/cursor.data"
#include "inc/images/clock_minute.data"
#include "inc/images/switch.data"
#include "inc/images/checked.data"
#include "inc/images/middle_off.data"
#include "inc/images/arrow_right_p.data"
#include "inc/images/ani9.data"
#include "inc/images/anib.data"
#include "inc/images/arrow_up_o.data"
#include "inc/images/clock.data"
#include "inc/images/empty.data"
#include "inc/images/ani5.data"
#include "inc/images/ani4.data"
#include "inc/images/left_off.data"
#include "inc/images/radio_unchecked.data"
#include "inc/images/rgba.data"
#include "inc/images/shifton.data"
#include "inc/images/arrow_up_n.data"
#include "inc/images/msg_active.data"
#include "inc/images/anic.data"
#include "inc/images/ani8.data"
#include "inc/images/guage_pointer.data"
#include "inc/images/right_off.data"
#include "inc/images/unmuted.data"
#include "inc/images/cross.data"
#include "inc/images/backspace.data"
#include "inc/images/arrow_left_p.data"
#include "inc/images/edit_clear_n.data"
#include "inc/images/clock_second.data"
#include "inc/images/contact.data"
#include "inc/images/bricks.data"
#include "inc/images/dialog_title.data"
#include "inc/images/ani7.data"
#include "inc/images/play_p.data"
#include "inc/images/green_btn_p.data"
#include "inc/images/red_btn_p.data"
#include "inc/images/me.data"
#include "inc/images/arrow_down_p.data"
#include "inc/images/warn.data"
#include "inc/images/contact_active.data"
#include "inc/images/slider_drag_o.data"
#include "inc/images/ani6.data"
#include "inc/images/message.data"
#include "inc/images/edit_clear_o.data"
#include "inc/images/ania.data"
#include "inc/images/ani1.data"
#include "inc/images/logo.data"
#include "inc/images/arrow_left_o.data"
#include "inc/images/2.data"
#include "inc/images/check.data"
#include "inc/images/middle_on.data"
#include "inc/images/arrow_down_o.data"
#include "inc/images/radio_checked.data"
#include "inc/images/red_btn_o.data"
#include "inc/images/green_btn_o.data"
#include "inc/images/slider_v_bg.data"
#include "inc/images/clock_hour.data"
#include "inc/images/play_o.data"
#include "inc/images/play_n.data"
#include "inc/images/slider_drag.data"
#include "inc/images/unchecked.data"
#include "inc/images/green_btn_n.data"
#include "inc/images/red_btn_n.data"
#include "inc/images/slider_drag_p.data"
#include "inc/images/slider_v_fg.data"
#include "inc/images/arrow_down_n.data"
#include "inc/images/info.data"
#include "inc/images/msg.data"
#include "inc/images/3.data"
#include "inc/images/arrow_left_n.data"
#include "inc/images/edit_clear_p.data"
#endif /*WITH_STB_IMAGE*/
#ifdef WITH_STB_FONT
#ifdef WITH_MINI_FONT
#include "inc/fonts/default.mini.res"
#else /*WITH_MINI_FONT*/
#include "inc/fonts/default.res"
#endif /*WITH_MINI_FONT*/
#else  /*WITH_STB_FONT*/
#include "inc/fonts/default.data"
#endif /*WITH_STB_FONT*/
#endif /*WITH_FS_RES*/

ret_t assets_init(void) {
  assets_manager_t* rm = assets_manager();

#ifdef WITH_FS_RES
  assets_manager_load(rm, ASSET_TYPE_STYLE, "default");
  assets_manager_load(rm, ASSET_TYPE_FONT, "default");
#else
  assets_manager_add(rm, ui_kb_ascii);
  assets_manager_add(rm, ui_rich_text1);
  assets_manager_add(rm, ui_color_picker_simple);
  assets_manager_add(rm, ui_combo_box);
  assets_manager_add(rm, ui_kb_phone);
  assets_manager_add(rm, ui_main);
  assets_manager_add(rm, ui_scroll_bar);
  assets_manager_add(rm, ui_lua);
  assets_manager_add(rm, ui_preload);
  assets_manager_add(rm, ui_images);
  assets_manager_add(rm, ui_edit);
  assets_manager_add(rm, ui_locale);
  assets_manager_add(rm, ui_kb_int);
  assets_manager_add(rm, ui_tab_control);
  assets_manager_add(rm, ui_animation);
  assets_manager_add(rm, ui_keyboard);
  assets_manager_add(rm, ui_kb_hex);
  assets_manager_add(rm, ui_color);
  assets_manager_add(rm, ui_color_picker);
  assets_manager_add(rm, ui_switch);
  assets_manager_add(rm, ui_dragger);
  assets_manager_add(rm, ui_dialog2);
  assets_manager_add(rm, ui_color_picker_hsv);
  assets_manager_add(rm, ui_tab_bottom);
  assets_manager_add(rm, ui_list_view_m);
  assets_manager_add(rm, ui_calibration_win);
  assets_manager_add(rm, ui_memtest);
  assets_manager_add(rm, ui_kb_float);
  assets_manager_add(rm, ui_htranslate);
  assets_manager_add(rm, ui_list_view_vh);
  assets_manager_add(rm, ui_rich_text);
  assets_manager_add(rm, ui_scroll_view);
  assets_manager_add(rm, ui_tab_list);
  assets_manager_add(rm, ui_animator);
  assets_manager_add(rm, ui_scroll_view_h);
  assets_manager_add(rm, ui_scroll_bar_h);
  assets_manager_add(rm, ui_spinbox);
  assets_manager_add(rm, ui_text_selector);
  assets_manager_add(rm, ui_big_font);
  assets_manager_add(rm, ui_tab_top_compact);
  assets_manager_add(rm, ui_slide_view_h);
  assets_manager_add(rm, ui_selectm);
  assets_manager_add(rm, ui_list_view);
  assets_manager_add(rm, ui_basic);
  assets_manager_add(rm, ui_auto_play);
  assets_manager_add(rm, ui_guage);
  assets_manager_add(rm, ui_color_picker_full);
  assets_manager_add(rm, ui_dialog1);
  assets_manager_add(rm, ui_fade);
  assets_manager_add(rm, ui_image_list);
  assets_manager_add(rm, ui_select1);
  assets_manager_add(rm, ui_bottom);
  assets_manager_add(rm, ui_image_animation);
  assets_manager_add(rm, ui_slide_view);
  assets_manager_add(rm, ui_time_clock);
  assets_manager_add(rm, ui_tab_top);
  assets_manager_add(rm, ui_slide_view_v);
  assets_manager_add(rm, ui_top);
  assets_manager_add(rm, ui_button);
  assets_manager_add(rm, ui_list_view_d);
  assets_manager_add(rm, ui_vtranslate);
  assets_manager_add(rm, ui_kb_ufloat);
  assets_manager_add(rm, ui_kb_default);
  assets_manager_add(rm, ui_rich_text2);
  assets_manager_add(rm, ui_list_view_h);
  assets_manager_add(rm, ui_color_picker_rgb);
  assets_manager_add(rm, ui_tab_bottom_compact);
  assets_manager_add(rm, ui_kb_uint);
  assets_manager_add(rm, ui_scroll_view_v);
  assets_manager_add(rm, image_arrow_right_o);
  assets_manager_add(rm, image_slider_bg);
  assets_manager_add(rm, image_ani3);
  assets_manager_add(rm, image_muted);
  assets_manager_add(rm, image_earth);
  assets_manager_add(rm, image_shift);
  assets_manager_add(rm, image_arrow_up_p);
  assets_manager_add(rm, image_bg800x480);
  assets_manager_add(rm, image_discovery_active);
  assets_manager_add(rm, image_right_on);
  assets_manager_add(rm, image_discovery);
  assets_manager_add(rm, image_rgb);
  assets_manager_add(rm, image_ani2);
  assets_manager_add(rm, image_find);
  assets_manager_add(rm, image_slider_fg);
  assets_manager_add(rm, image_left_on);
  assets_manager_add(rm, image_1);
  assets_manager_add(rm, image_question);
  assets_manager_add(rm, image_guage_bg);
  assets_manager_add(rm, image_arrow_right_n);
  assets_manager_add(rm, image_clock_bg);
  assets_manager_add(rm, image_me_active);
  assets_manager_add(rm, image_cursor);
  assets_manager_add(rm, image_clock_minute);
  assets_manager_add(rm, image_switch);
  assets_manager_add(rm, image_checked);
  assets_manager_add(rm, image_middle_off);
  assets_manager_add(rm, image_arrow_right_p);
  assets_manager_add(rm, image_ani9);
  assets_manager_add(rm, image_anib);
  assets_manager_add(rm, image_arrow_up_o);
  assets_manager_add(rm, image_clock);
  assets_manager_add(rm, image_empty);
  assets_manager_add(rm, image_ani5);
  assets_manager_add(rm, image_ani4);
  assets_manager_add(rm, image_left_off);
  assets_manager_add(rm, image_radio_unchecked);
  assets_manager_add(rm, image_rgba);
  assets_manager_add(rm, image_shifton);
  assets_manager_add(rm, image_arrow_up_n);
  assets_manager_add(rm, image_msg_active);
  assets_manager_add(rm, image_anic);
  assets_manager_add(rm, image_ani8);
  assets_manager_add(rm, image_guage_pointer);
  assets_manager_add(rm, image_right_off);
  assets_manager_add(rm, image_unmuted);
  assets_manager_add(rm, image_cross);
  assets_manager_add(rm, image_backspace);
  assets_manager_add(rm, image_arrow_left_p);
  assets_manager_add(rm, image_edit_clear_n);
  assets_manager_add(rm, image_clock_second);
  assets_manager_add(rm, image_contact);
  assets_manager_add(rm, image_bricks);
  assets_manager_add(rm, image_dialog_title);
  assets_manager_add(rm, image_ani7);
  assets_manager_add(rm, image_play_p);
  assets_manager_add(rm, image_green_btn_p);
  assets_manager_add(rm, image_red_btn_p);
  assets_manager_add(rm, image_me);
  assets_manager_add(rm, image_arrow_down_p);
  assets_manager_add(rm, image_warn);
  assets_manager_add(rm, image_contact_active);
  assets_manager_add(rm, image_slider_drag_o);
  assets_manager_add(rm, image_ani6);
  assets_manager_add(rm, image_message);
  assets_manager_add(rm, image_edit_clear_o);
  assets_manager_add(rm, image_ania);
  assets_manager_add(rm, image_ani1);
  assets_manager_add(rm, image_logo);
  assets_manager_add(rm, image_arrow_left_o);
  assets_manager_add(rm, image_2);
  assets_manager_add(rm, image_check);
  assets_manager_add(rm, image_middle_on);
  assets_manager_add(rm, image_arrow_down_o);
  assets_manager_add(rm, image_radio_checked);
  assets_manager_add(rm, image_red_btn_o);
  assets_manager_add(rm, image_green_btn_o);
  assets_manager_add(rm, image_slider_v_bg);
  assets_manager_add(rm, image_clock_hour);
  assets_manager_add(rm, image_play_o);
  assets_manager_add(rm, image_play_n);
  assets_manager_add(rm, image_slider_drag);
  assets_manager_add(rm, image_unchecked);
  assets_manager_add(rm, image_green_btn_n);
  assets_manager_add(rm, image_red_btn_n);
  assets_manager_add(rm, image_slider_drag_p);
  assets_manager_add(rm, image_slider_v_fg);
  assets_manager_add(rm, image_arrow_down_n);
  assets_manager_add(rm, image_info);
  assets_manager_add(rm, image_msg);
  assets_manager_add(rm, image_3);
  assets_manager_add(rm, image_arrow_left_n);
  assets_manager_add(rm, image_edit_clear_p);
  assets_manager_add(rm, style_edit);
  assets_manager_add(rm, style_keyboard);
  assets_manager_add(rm, style_color);
  assets_manager_add(rm, style_tab_bottom);
  assets_manager_add(rm, style_calibration);
  assets_manager_add(rm, style_tab_list);
  assets_manager_add(rm, style_default);
  assets_manager_add(rm, style_big_font);
  assets_manager_add(rm, style_tab_top_compact);
  assets_manager_add(rm, style_dialog);
  assets_manager_add(rm, style_tab_top);
  assets_manager_add(rm, style_button);
  assets_manager_add(rm, style_tab_bottom_compact);
  assets_manager_add(rm, font_default);
#endif

  tk_init_assets();
  return RET_OK;
}
