import os

env=DefaultEnvironment().Clone();
BIN_DIR=os.environ['BIN_DIR'];
LIB_DIR=os.environ['LIB_DIR'];

env.Library(os.path.join(LIB_DIR, 'assets'), ['assets.c']);

env['LIBS'] = ['assets'] + env['LIBS']
env['LINKFLAGS'] = env['OS_SUBSYSTEM_WINDOWS'] + env['LINKFLAGS'];

env.Program(os.path.join(BIN_DIR, 'demo1'), ['demo1_app.c']);
env.Program(os.path.join(BIN_DIR, 'demovg'), ['demo_vg_app.c']);
env.Program(os.path.join(BIN_DIR, 'demoui'), ['demo_ui_app.c']);
env.Program(os.path.join(BIN_DIR, 'demotr'), ['demo_tr_app.c']);
env.Program(os.path.join(BIN_DIR, 'demo_basic'), ['demo_basic.c']);
env.Program(os.path.join(BIN_DIR, 'demo_thread'), ['demo_thread_app.c']);
env.Program(os.path.join(BIN_DIR, 'demo_animator'), ['demo_animator_app.c']);

env.Program(os.path.join(BIN_DIR, 'preview_ui'), ['preview_ui.c']);
env.Program(os.path.join(BIN_DIR, 'demo_desktop'), ['demo_desktop.c']);
env.Program(os.path.join(BIN_DIR, 'demo_file_browser'), ['demo_file_browser.c']);
env.Program(os.path.join(BIN_DIR, 'demo_canvas_offline'), ['demo_canvas_offline.c']);
