import os
import copy

BIN_DIR=os.environ['BIN_DIR'];
LIB_DIR=os.environ['LIB_DIR'];

sources=Glob('base/*.c') +\
  Glob('ui_loader/*.c') + \
  Glob('xml/*.c') + \
  Glob('font/*.c') + \
  Glob('blend/*.c') + \
  Glob('image_loader/*.c') + \
  Glob('widget_animators/*.c') + \
  Glob('platforms/pc/*.c') + \
  ['tk.c'];

sources += ['main_loop/main_loop_simple.c'];
if os.environ['LCD'] == 'NANOVG':
  sources += ['window_animators/window_animator_nanovg.c'];
  sources += ['lcd/lcd_nanovg.c', 'main_loop/main_loop_nanovg.c'];
else:
  sources += ['window_animators/window_animator_fb.c'];
  sources += ['lcd/lcd_sdl2.c', 'main_loop/main_loop_sdl2.c']

if os.environ['FRAME_BUFFER_FORMAT'] =='rgba8888':
  sources += ['lcd/lcd_mem_rgba8888.c'];
else:
  sources += ['lcd/lcd_mem_rgb565.c'];

if os.environ['VGCANVAS'] == 'NANOVG':
  sources += Glob('vgcanvas/vgcanvas_nanovg.c')
elif os.environ['VGCANVAS'] == 'AGG':
  sources += Glob('vgcanvas/vgcanvas_agg.cpp')
else:
  sources += Glob('vgcanvas/vgcanvas_picasso.cpp')

env=DefaultEnvironment().Clone()
env.Library(os.path.join(LIB_DIR, 'awtk'), sources)
