import os
import copy
import awtk_config as awtk

BIN_DIR=os.environ['BIN_DIR'];
LIB_DIR=os.environ['LIB_DIR'];

sources = Glob('buffered/*.c') + Glob('file/*.c') \
  +  Glob('inet/*.c') +  Glob('mem/*.c') +  Glob('serial/*.c') \
  +  Glob('shdlc/*.c') + Glob('noisy/*.c') + Glob('misc/*.c') + Glob('statistics/*.c'); 

env=DefaultEnvironment().Clone()

env.Library(os.path.join(LIB_DIR, 'streams'), sources, LIBS=['tkc'])

