import os
import sys

env=DefaultEnvironment().Clone()
BIN_DIR=os.environ['BIN_DIR'];
LIB_DIR=os.environ['LIB_DIR'];
env['LIBS'] = ['theme_gen', 'common'] + env['LIBS'];
env['LINKFLAGS'] = env['OS_SUBSYSTEM_CONSOLE'] + env['LINKFLAGS'];

env.Program(os.path.join(BIN_DIR, 'bsvggen'), ['bsvg_gen.cc'])
env.Program(os.path.join(BIN_DIR, 'bsvgdump'), ['bsvg_dump.cc'])



