
FREETYPE_LIBS=-lfreetype -lz

CC=gcc -g -pg
#CC=gcc -O2
INC=-I../include -I../build
CFLAGS=

SYSTEM_LIBS = -lminigui -ljpeg -lpng ${FREETYPE_LIBS} -lpthread -lstdc++

gamma_objs = test.o gamma_func.o

alpha_objs = test.o alpha_func.o

gradient_objs = test.o gradient_func.o

composite_objs = test.o composite_func.o

clip_objs = test.o clip_func.o

gcstate_objs = test.o gcstate_func.o

text_objs = test.o text_func.o

pattern_objs = test.o pattern_func.o

shadow_objs = test.o shadow_func.o

blur_objs = test.o blur_func.o

mask_objs = test.o mask_func.o

part_objs = test.o part_func.o

bitblt_objs = test.o bitblt_func.o

path_objs = test.o path_func.o

all: gamma.exe alpha.exe gradient.exe composite.exe clip.exe gcstate.exe pattern.exe text.exe shadow.exe blur.exe mask.exe part.exe bitblt.exe path.exe

alpha.exe : ${alpha_objs}
	${CC} ${alpha_objs} ../src/libpicasso.a -o $@ ${INC} ${SYSTEM_LIBS}

gamma.exe : ${gamma_objs}
	${CC} ${gamma_objs} ../src/libpicasso.a -o $@ ${INC} ${SYSTEM_LIBS}

gradient.exe : ${gradient_objs}
	${CC} ${gradient_objs} ../src/libpicasso.a -o $@ ${INC} ${SYSTEM_LIBS}

composite.exe : ${composite_objs}
	${CC} ${composite_objs} ../src/libpicasso.a -o $@ ${INC} ${SYSTEM_LIBS}

clip.exe : ${clip_objs}
	${CC} ${clip_objs} ../src/libpicasso.a -o $@ ${INC} ${SYSTEM_LIBS}

gcstate.exe : ${gcstate_objs}
	${CC} ${gcstate_objs} ../src/libpicasso.a -o $@ ${INC} ${SYSTEM_LIBS}

text.exe : ${text_objs}
	${CC} ${text_objs} ../src/libpicasso.a -o $@ ${INC} ${SYSTEM_LIBS}

pattern.exe : ${pattern_objs}
	${CC} ${pattern_objs} ../src/libpicasso.a -o $@ ${INC} ${SYSTEM_LIBS}

shadow.exe : ${shadow_objs}
	${CC} ${shadow_objs} ../src/libpicasso.a -o $@ ${INC} ${SYSTEM_LIBS}

blur.exe : ${blur_objs}
	${CC} ${blur_objs} ../src/libpicasso.a -o $@ ${INC} ${SYSTEM_LIBS}

mask.exe : ${mask_objs}
	${CC} ${mask_objs} ../src/libpicasso.a -o $@ ${INC} ${SYSTEM_LIBS}

part.exe : ${part_objs}
	${CC} ${part_objs} ../src/libpicasso.a -o $@ ${INC} ${SYSTEM_LIBS}

bitblt.exe : ${bitblt_objs}
	${CC} ${bitblt_objs} ../src/libpicasso.a -o $@ ${INC} ${SYSTEM_LIBS}

path.exe : ${path_objs}
	${CC} ${path_objs} ../src/libpicasso.a -o $@ ${INC} ${SYSTEM_LIBS}

alpha_func.o : alpha_func.c
	${CC} ${CFLAGS} -c $< -o $@ ${INC}

gamma_func.o : gamma_func.c
	${CC} ${CFLAGS} -c $< -o $@ ${INC}

gradient_func.o : gradient_func.c
	${CC} ${CFLAGS} -c $< -o $@ ${INC}

composite_func.o : composite_func.c
	${CC} ${CFLAGS} -c $< -o $@ ${INC}

clip_func.o : clip_func.c
	${CC} ${CFLAGS} -c $< -o $@ ${INC}

gcstate_func.o : gcstate_func.c
	${CC} ${CFLAGS} -c $< -o $@ ${INC}

text_func.o : text_func.c
	${CC} ${CFLAGS} -c $< -o $@ ${INC}

pattern_func.o : pattern_func.c
	${CC} ${CFLAGS} -c $< -o $@ ${INC}

shadow_func.o : shadow_func.c
	${CC} ${CFLAGS} -c $< -o $@ ${INC}

blur_func.o : blur_func.c
	${CC} ${CFLAGS} -c $< -o $@ ${INC}

mask_func.o : mask_func.c
	${CC} ${CFLAGS} -c $< -o $@ ${INC}

part_func.o : part_func.c
	${CC} ${CFLAGS} -c $< -o $@ ${INC}

bitblt_func.o : bitblt_func.c
	${CC} ${CFLAGS} -c $< -o $@ ${INC}

path_func.o : path_func.c
	${CC} ${CFLAGS} -c $< -o $@ ${INC}

test.o : testMg.c
	${CC} ${CFLAGS} -c $< -o $@ ${INC}

clean:
	rm *.o *.exe *.out
